language: python
python:
  - "3.8"
cache: pip
install:
  - pip install pipenv 
  - pipenv install --dev
script:
  - pipenv run flake8 .
  - pipenv run mypy .
  - pipenv run pytest tests/
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
